name: 定时运行 my.py

# 触发条件：每10分钟运行一次，同时支持手动触发
on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟执行一次（cron语法：分 时 日 月 周）
  workflow_dispatch:  # 允许在GitHub页面手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新版Ubuntu系统

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4  # 拉取当前仓库代码到运行环境

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 可根据需要修改Python版本（如3.10、3.11等）

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip  # 升级pip
          pip install requests pycryptodome  # 安装所需依赖

      - name: 运行my.py脚本
        run: python my.py  # 执行脚本（如果脚本在子目录，需写路径如：python my/my.py）
